//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.UI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GitHubResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GitHubResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitHub.UI.GitHubResources", typeof(GitHubResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string TwoFactorApp {
            get {
                return ResourceManager.GetString("TwoFactorApp", resourceCulture);
            }
        }
        
        internal static string TwoFactorSms {
            get {
                return ResourceManager.GetString("TwoFactorSms", resourceCulture);
            }
        }
        
        internal static string TwoFactorTitle {
            get {
                return ResourceManager.GetString("TwoFactorTitle", resourceCulture);
            }
        }
        
        internal static string TwoFactorUnknown {
            get {
                return ResourceManager.GetString("TwoFactorUnknown", resourceCulture);
            }
        }
        
        internal static string DeviceCodeTitle {
            get {
                return ResourceManager.GetString("DeviceCodeTitle", resourceCulture);
            }
        }
        
        internal static string DeviceCodeDescription {
            get {
                return ResourceManager.GetString("DeviceCodeDescription", resourceCulture);
            }
        }
        
        internal static string DeviceCodeAutoCloseMessage {
            get {
                return ResourceManager.GetString("DeviceCodeAutoCloseMessage", resourceCulture);
            }
        }
        
        internal static string DeviceCodeExpiryMessageFormat {
            get {
                return ResourceManager.GetString("DeviceCodeExpiryMessageFormat", resourceCulture);
            }
        }
    }
}
